use_frameworks!

platform :ios, '9.0'

target 'MapModuleSDK_Example' do
  pod 'MapModuleSDK', :path => '../'

  target 'MapModuleSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
